### ISSUE TITLE
win子系统ubuntu运行出错

### ISSUE THREAD

**Issue by jmmes** [totoroterror/warp-cloner#10]
Traceback (most recent call last):
  File "/home/vip/warp-cloner/src/main.py", line 8, in <module>
    from warp import clone_key, GetInfoData
  File "/home/vip/warp-cloner/src/warp.py", line 1, in <module>
    from distutils.command.config import config
ModuleNotFoundError: No module named 'distutils.command'

**Comment by totoroterror** [comment]
It should work now, try.
